version: '3.4'

services:
  database:
    image: postgres:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_database
    environment:
      POSTGRES_DB: ${DB_DATABASE:-app}
      # You should definitely change the password in production
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-!ChangeMe!}
#      PGDATA: /data/postgres
      # Default path is
      # PGDATA: /var/lib/postgresql/data
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./db/data:/var/lib/postgresql/data:rw
    ports:
      - "${COMPOSE_IP}:${COMPOSE_PORT_DB}:${DB_PORT}"
    restart: unless-stopped

  php:
    build:
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_php
    depends_on:
      - database
#    environment:
#      DATABASE_URL: postgresql://${DB_USER:-app}:${DB_PASS:-!ChangeMe!}@postgres:5432/${DB_DATABASE:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
    volumes:
      - ../../:/var/www/
      - ./php/etc/php-development.ini:/usr/local/etc/php/php.ini
      - ./php/etc/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#       Better performance?
#      - /var/www

  nginx:
    image: nginx:1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    depends_on:
      - php
    ports:
      - "${COMPOSE_IP}:${COMPOSE_PORT_HTTP}:80"
      - "${COMPOSE_IP}:8143:443"
    volumes:
      - ../../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled

volumes:
  database_data: